spring:
  # let ControllerAdvice handle missing mappings NoHandlerFoundException
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
url:
  get-order: /v1-0/order/
  post-order: /v1-0/order/new